void init_liste();
int liste_vide();
int hors_liste();
void en_tete();
void en_queue();
void suivant();
void precedent();
void valeur_elt(int *v);
void modif_elt(int v);
void oter_elt();
void ajout_droit(int v);
void ajout_gauche(int v);